"""dat-s writing and SDPA output parsing (pure functions, no binary)."""

from __future__ import annotations

import numpy as np
import pytest
from sympy import Symbol

from ncpolopt.sdp_problem import SdpBuilder
from ncpolopt.sdpa_writer import (
    parse_solution_matrix,
    read_sdpa_out,
    write_dat_s,
)


def _small_problem(complex_matrix: bool = False):
    """A 2x2 moment block with two variables and a constant corner."""
    x0, x1 = Symbol("x0"), Symbol("x1")
    builder = SdpBuilder([2], normalized=True, complex_matrix=complex_matrix)
    builder.add_entry(0, 0, 0, 0, 1.0)
    k0 = builder.new_variable(x0, 0, 0, 1)
    builder.add_entry(0, 0, 1, k0, 1.0)
    k1 = builder.new_variable(x1, 0, 1, 1)
    builder.add_entry(0, 1, 1, k1, 1.0)
    builder.set_objective([0.0, 1.0, -0.5])
    return builder.freeze(1, {}, ())


def test_write_dat_s_real(tmp_path) -> None:
    """The real .dat-s text matches the SDPA format conventions."""
    problem = _small_problem()
    filename = tmp_path / "problem.dat-s"
    write_dat_s(problem, str(filename))
    text = filename.read_text()
    assert f'"file {filename} generated by ncpolopt"' in text
    assert "2 = number of vars" in text
    assert "1 = number of blocs" in text
    assert "(2) = BlocStructure" in text
    assert "{1.0, -0.5}" in text
    # Constant entries are negated (SDPA's F0 convention).
    assert "\t1\t1\t1\t-1.0" in text
    # Variable entries keep their coefficient.
    assert "1\t1\t2\t1.0" in text  # x0 at (1, 2)
    assert "1\t2\t2\t1.0" in text  # x1 at (2, 2)


def test_write_dat_s_complex(tmp_path) -> None:
    """Complex problems double the variable count and block sizes."""
    problem = _small_problem(complex_matrix=True)
    filename = tmp_path / "complex.dat-s"
    write_dat_s(problem, str(filename))
    text = filename.read_text()
    assert "4 = number of vars" in text
    assert "(4) = BlocStructure" in text
    objective = text.split("{", 1)[1].split("}", 1)[0]
    assert objective.count("1.0") == 2 and objective.count("-0.5") == 2


def test_write_dat_s_complex_imaginary_entries(tmp_path) -> None:
    """Imaginary parts land in the off-diagonal entries of the doubled block."""
    x = Symbol("x")
    builder = SdpBuilder([2], normalized=True, complex_matrix=True)
    k = builder.new_variable(x, 0, 0, 1)
    builder.add_entry(0, 0, 1, k, 1.0 + 2.0j)
    builder.set_objective([0.0, 1.0])
    problem = builder.freeze(1, {}, ())
    filename = tmp_path / "imag.dat-s"
    write_dat_s(problem, str(filename))
    text = filename.read_text()
    assert "2 = number of vars" in text
    assert "(4) = BlocStructure" in text
    # Real part at (1, 2), mirrored at (3, 4) inside the same doubled block.
    assert "1\t1\t1\t2\t1.0" in text
    assert "1\t1\t3\t4\t1.0" in text
    # Imaginary part at (1, 4) and its mirror (2, 3) with opposite signs,
    # matching the layout the original ncpol2sdpa writer produced.
    assert "2\t1\t1\t4\t2.0" in text
    assert "2\t1\t2\t3\t-2.0" in text


def test_parse_solution_matrix_multiblock() -> None:
    """The parser reconstructs per-block matrices from SDPA row syntax."""
    lines = [
        "xMat =\n",
        "{\n",
        "{{1.0, 0.0},\n",
        "{0.0, 1.0}}\n",
        "{\n",
        "{0.5}}\n",
        "}\n",
    ]
    matrices = parse_solution_matrix(iter(lines))
    assert len(matrices) == 2
    assert np.allclose(matrices[0], np.eye(2))
    assert np.allclose(matrices[1], [[0.5]])


def test_read_sdpa_out_full(tmp_path) -> None:
    """Objective values, status and matrices are extracted."""
    filename = tmp_path / "sdpa.out"
    filename.write_text(
        "objValPrimal = 1.5000000000e+00\n"
        "objValDual = 1.4999999999e+00\n"
        "phase.value = pdOPT\n"
        "xMat =\n"
        "{\n"
        "{{1.0, 0.0},\n"
        "{0.0, 1.0}}\n"
        "}\n"
        "yMat =\n"
        "{\n"
        "{2.0}}\n"
        "}\n"
    )
    solution = read_sdpa_out(str(filename))
    assert solution.primal == pytest.approx(1.5)
    assert solution.dual == pytest.approx(1.5)
    assert solution.status == "optimal"
    assert np.allclose(solution.x_mat[0], np.eye(2))
    assert np.allclose(solution.y_mat[0], [[2.0]])


def test_read_sdpa_out_missing_values_is_invalid(tmp_path) -> None:
    """Missing objective values or matrices flag the status as invalid."""
    filename = tmp_path / "broken.out"
    filename.write_text("phase.value = pdOPT\n")
    solution = read_sdpa_out(str(filename))
    assert solution.status == "invalid"
    assert solution.primal is None

    filename2 = tmp_path / "missing-mats.out"
    filename2.write_text(
        "objValPrimal = 1.0\nobjValDual = 1.0\nphase.value = pdOPT\n"
    )
    assert read_sdpa_out(str(filename2)).status == "invalid"


def test_read_sdpa_out_status_phases() -> None:
    """All SDPA phase markers map to their status strings."""
    from ncpolopt.sdpa_writer import _parse_phase

    assert _parse_phase("phase.value = pdOPT") == "optimal"
    assert _parse_phase("phase.value = pFEAS") == "primal feasible"
    assert _parse_phase("phase.value = dINF") == "infeasible"
    assert _parse_phase("phase.value = pdUNBD") == "unbounded"
    assert _parse_phase("phase.value = ???") == "unknown"
