"""Part B: verify the moment-matrix relaxation of eq. (14) of the document.

Two constructions of the relaxation are exercised:

* The verbatim form (``verbatim_relaxation_value``): the two moment
  matrices ``M = Gamma^{(J_M)}`` and ``L = Gamma^{(Z)}`` over the word
  basis, parametrized by the functional classes
  ``G_{u,v} = Tr_{B2}(v u^dagger)`` and
  ``H_{u,v} = Tr_{A0 B2}(v u^dagger)`` (each class is one SDP variable),
  with the correlations pinned at ``M[V_alpha, U_{x,y}] = p(alpha|x,y)/d``
  and the constraints ``M >= 0, L >= 0, L - M >= 0``.
* The factored NPA-tau re-expression (``npa_tau_relaxation_value``): the
  same relaxation written as a standard NPA problem over the factored
  algebra ``{rho, sigma, v, J, W}`` with state tau = I/8 (Brown-style
  commutation ``rho_i sigma_j -> sigma_j rho_i``; the SDP is shrunk by
  the orthogonality rules ``rho_0 rho_1 -> 0``, ``sigma_0 sigma_1 -> 0``
  for the orthogonal input states |0> and |1>), with the functional-class
  structure encoded as moment-matrix equalities generated by
  ``ncpolopt.hierarchies.class_moment_equalities``. The single-output
  variant solves through the package's cvxpy backend; the 4-output
  variant (``--n-outputs 4``) through the package's direct sparse
  CLARABEL backend (``solver="clarabel"``).

Each certified value must be a lower bound on the Choi fidelity ``p``
and strictly positive (non-degenerate). The factored solves take on the
order of minutes (8-25 for the 4-output variant).

Usage: ``uv run python examples/quantum_memory/verify_relaxation.py
[--p-grid 0.25,0.5,1.0] [--n-outputs 4]``
"""

from __future__ import annotations

import argparse
import logging
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))

from common import (
    npa_tau_relaxation_value,
    verbatim_relaxation_value,
)

logger = logging.getLogger(__name__)

BOUND_TOL = 1e-5


def _check(condition: bool, *context: object) -> None:
    """Fail the verification with context when ``condition`` is false.

    A plain raise instead of ``assert``, so the checks are not stripped
    under ``python -O``.

    Args:
        condition: The verification condition.
        *context: Values reported on failure.

    Raises:
        RuntimeError: If ``condition`` is false.
    """
    if not condition:
        raise RuntimeError(f"verification failed: {context}")


def run(p: float, n_outputs: int) -> None:
    """Solve all relaxation variants for one channel parameter.

    Args:
        p: The channel parameter.
        n_outputs: The measurement outputs for the factored L2 solves
            (1 or 4; the verbatim level-1 rows run for both in any case).
    """
    logger.info("--- p = %.4f ---", p)

    verbatim_1 = verbatim_relaxation_value(p, n_outputs=1, level=1)
    verbatim_1_tp = verbatim_relaxation_value(p, n_outputs=1, level=1, tp_pin=True)
    verbatim_4 = verbatim_relaxation_value(p, n_outputs=4, level=1)
    verbatim_4_tp = verbatim_relaxation_value(p, n_outputs=4, level=1, tp_pin=True)
    logger.info(
        "verbatim  single-output L1 = %.6f  L1+TP = %.6f | 4-output L1 = %.6f  L1+TP = %.6f",
        verbatim_1,
        verbatim_1_tp,
        verbatim_4,
        verbatim_4_tp,
    )

    # The factored NPA-tau re-expression at level 2: the functional-class
    # equalities of eqs. (12)/(13) enter as block-0 moment-matrix
    # equalities at first-occurrence positions, and the objective is
    # minimized over the W-localizing block (with and without the
    # trace-preserving pin <J> = 1/4).
    npa_tau = npa_tau_relaxation_value(p, tp_pin=False, solver="cvxpy", n_outputs=n_outputs)
    npa_tau_tp = npa_tau_relaxation_value(p, tp_pin=True, solver="cvxpy", n_outputs=n_outputs)
    logger.info(
        "factored NPA-tau L2 (n_outputs=%d) = %.6f  L2+TP = %.6f",
        n_outputs,
        npa_tau,
        npa_tau_tp,
    )

    # Every certified value is a valid lower bound and non-degenerate.
    for name, value in (
        ("verbatim L1", verbatim_1),
        ("verbatim L1+TP", verbatim_1_tp),
        ("verbatim 4-output L1", verbatim_4),
        ("verbatim 4-output L1+TP", verbatim_4_tp),
        (f"factored NPA-tau L2 (n_outputs={n_outputs})", npa_tau),
        (f"factored NPA-tau L2+TP (n_outputs={n_outputs})", npa_tau_tp),
    ):
        _check(value <= p + BOUND_TOL, name, value, p)
        _check(value > 1e-6, name, value)
    logger.info("all bounds certified (<= p + %.0e, non-degenerate)", BOUND_TOL)


def main() -> None:
    """Parse arguments and run the checks."""
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("--p", type=float, default=None, help="single channel parameter")
    parser.add_argument(
        "--p-grid", type=str, default="0.5", help="comma-separated grid (the README table uses 0.25,0.3,0.5,0.75,1.0)"
    )
    parser.add_argument(
        "--n-outputs", type=int, choices=[1, 4], default=1,
        help="measurement outputs of the factored L2 solves (default 1)",
    )
    args = parser.parse_args()
    logging.basicConfig(level=logging.INFO, format="%(message)s")
    values = [args.p] if args.p is not None else [float(v) for v in args.p_grid.split(",")]
    for p in values:
        run(p, args.n_outputs)
    logger.info("All Part B checks passed.")


if __name__ == "__main__":
    main()
